apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nati-test
  namespace: argocd
spec:
  project: nati-project
  destination:
    server: https://kubernetes.default.svc
    namespace: natis-namespace
  sources:
    - chart: elasticsearch
      repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      path: guestbook
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true    # Automatically remove resources not declared in the source repository
      selfHeal: true # Automatically reapply manifests if they drift from the desired state
    syncOptions:
      - CreateNamespace=true
