apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: nati-test
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: helmfile-namespace
  sources:
    - repoURL: https://github.com/NathanelLevi/helmfile-demo.git
      path: helmfiles
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true    # Automatically remove resources not declared in the source repository
      selfHeal: true # Automatically reapply manifests if they drift from the desired state
    syncOptions:
      - CreateNamespace=true
